[pytest]
# Добавляем аргументы командной строки по умолчанию
addopts = 
    -v
    --alluredir=allure-results
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure

# Регистрируем кастомные маркеры (чтобы pytest не ругался на них в будущем)
markers =
    e2e: End-to-end тесты
    ui: UI тесты