name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Выдаем боту права на пуш отчета в ветку gh-pages
permissions:
  contents: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Шаг 1. Копирование кода из репозитория
      uses: actions/checkout@v4

    - name: Шаг 2. Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Шаг 3. Установка менеджера пакетов Poetry
      run: pip install poetry

    - name: Шаг 4. Установка зависимостей проекта
      run: poetry install

    - name: Шаг 5. Установка браузера Chromium для Playwright
      run: poetry run playwright install --with-deps chromium

    - name: Шаг 6. Запуск автотестов
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        STANDARD_USER: ${{ secrets.STANDARD_USER }}
        LOCKED_OUT_USER: ${{ secrets.LOCKED_OUT_USER }}
        PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
        VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      run: poetry run pytest -v

    - name: Шаг 7. Генерация Allure отчета
      uses: simple-elf/allure-report-action@master
      if: always() # Важно! Генерируем отчет даже если тесты упали
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20 # Хранить историю последних 20 запусков

    - name: Шаг 8. Публикация отчета на GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history